image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

environment:
  MSBUILD_LOGGER: C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll

build_script:
  - msbuild Moq.sln /r /t:Build;Test;Pack /logger:"%MSBUILD_LOGGER%"

test: off

deploy:
  - provider: NuGet
    api_key:
      secure: 5dsPohRA1/Bm/yD1DTUDZ5ZUAH7+jjWWcy6wnFZrWDKG4C8VOInfdWj/71SZgHYG
    on:
      appveyor_repo_tag: true

nuget:
  project_feed: true

artifacts:
  - path: 'out\*.nupkg'
